apiVersion: apps/v1
kind: Deployment
metadata:
    name: finaltest35-admin-backend-test-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: finaltest35-admin-backend-test-frontend
    template:
        metadata:
            labels:
                app: finaltest35-admin-backend-test-frontend
        spec:
            imagePullSecrets:
                - name: dockerhub-secret
            containers:
                - name: finaltest35-admin-backend-test-frontend
                    image: devopspaxarisglobalrepo/finaltest35-admin-backend-test-frontend:8e885ed6355b5c137c1647d44c279aa776dc378e
                    imagePullPolicy: Always
                    ports:
                        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: finaltest35-admin-backend-test-frontend
spec:
    selector:
        app: finaltest35-admin-backend-test-frontend
    ports:
        - port: 80
            targetPort: 80
    type: ClusterIP
